### ISSUE TITLE
When there are a lot of files in node_modules  `readdir: 2369ms`

### ISSUE THREAD

**Issue by nimojs** [steveukx/readdir.js#4]
When there are a lot of files in node_modules

app.js
```js
var readdir = require('readdir')
console.time('readdir')
readdir.read(__dirname, ['/*.html'], function (err, filesArray) {
    console.log(filesArray)
    console.timeEnd('readdir')
})
```

package.json
```js
{
  "scripts": {
    "start": "node app.js"
  },
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-minify-css": "^1.0.0",
    "gulp-nodemon": "^2.0.3",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.4",
    "gulp-watch-path": "^0.1.0",
    "stream-combiner2": "^1.0.2"
  },
  "dependencies": {
    "nodeajax": "0.0.7",
    "readdir": "0.0.13"
  }
}

```

index.html
```html
<html>
<body></body>
</html>
```

```
$ npm install
$ node app
    [ 'index.html' ]
    readdir: 2369ms
```

```
node v0.12.2
mac 10.10
readdir v0.0.13
```

**Comment by nimojs** [comment]
Sorry,I missed the `readDir.NON_RECURSIVE`

use `readdir.INCLUDE_DIRECTORIES + readdir.NON_RECURSIVE,`

app.js
```
var readdir = require('readdir')
console.time('readdir')
readdir.read(__dirname, ['*.html'],  readdir.INCLUDE_DIRECTORIES + readdir.NON_RECURSIVE, function (err, filesArray) {
    console.log(filesArray)
    console.timeEnd('readdir')
})
```

**Comment by steveukx** [comment]
Sorry it took a while to get back to you, but glad you've sorted it now.

`readdir.INCLUDE_DIRECTORIES` will include directories in the returned results, ordinarily they are filtered out so the return values are just file paths. `readdir.NON_RECURSIVE` prevents `readdir` from walking through sub-directories when building the result set.

Currently there isn't a way to set ignored paths in the filter, I am thinking of adding that though which would allow for `grunt` style exclusions in the paths array that are prefixed with a `!`. If you want to follow progress on that, it's tracked at https://github.com/steveukx/readdir.js/issues/5
