### ISSUE TITLE
Add license field

### ISSUE THREAD

**Issue by gladziu90** [steveukx/readdir.js#6]
Hi. Is this intended that repository has no license field? 
If no then I have a request to add license. I need to decide if can use your package as MIT license or need to find other package.

thanks in advance

**Comment by steveukx** [comment]
Hi, thanks for pointing this out - it was just an oversight back when the library was released. [MIT licence](https://github.com/steveukx/readdir.js/blob/6d7384996123720682e4ed5e492725209ebdf402/package.json#L25) now added. Version 0.1.0 should now be available on [NPM](https://www.npmjs.com/package/readdir)

**Comment by gladziu90** [comment]
great, thank you!
